ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "telegramNotified" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "lastSyncError" TEXT;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "syncAttemptCount" INTEGER DEFAULT 0;
